{% set data = load_setup_py_data() %}

package:
    name: flexdata
    version: {{ data['version'] }}

source:
    path: ../

build:
    noarch: python
    number: 0
    script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-build-isolation --verbose

requirements:
    host:
        - python >=3.7
        - pip
        - setuptools
        - wheel

    run:
        - python >=3.7
        # dependencies are defined in setup.py
        {% for dep in data['install_requires'] %}
        - {{ dep.lower() }}
        {% endfor %}

about:
    home: https://github.com/cicwi/flexDATA
    license_file: LICENSE.md
    summary: "This project comprises IO routines for CT data."
