{% set data = load_setup_py_data() %}

package:
    name: flexdata
    version: {{ data['version'] }}

source:
    path: ../

build:
    number: '0'

requirements:
    build:
        - python {{ python }}
        - tifffile
        - pyqtgraph

    run:
        - python
        # dependencies are defined in setup.py
        {% for dep in data['install_requires'] %}
        - {{ dep.lower() }}
        {% endfor %}

about:
    home: https://github.com/cicwi/flexDATA
    license_file: LICENSE.md
    summary: "This project comprises IO routines for CT data."

extra:
    maintainers:
        - Alexander Kostenko
